// filepath: Phase2/cpu_uvc/cpu_logger.svh

`ifndef CPU_LOGGER_SVH
`define CPU_LOGGER_SVH

import uvm_pkg::*;
`include "uvm_macros.svh"

class cpu_logger extends uvm_component;
    `uvm_component_utils(cpu_logger)
    
    // ===== 配置 =====
    cpu_config m_config;
    
    // ===== UVM分析端口（接收monitor数据）=====
    uvm_analysis_imp #(cpu_seq_item, cpu_logger) analysis_export;
    
    // ===== 文件和统计 =====
    integer trace_fd;
    longint instruction_count;
    longint cycle_count;
    longint branch_count;
    longint branch_taken_count;      // 
    longint branch_not_taken_count;  // 
    longint load_count;
    longint store_count;
    longint exception_count;         // 
    bit file_opened;
    
    function new(string name = "cpu_logger", uvm_component parent = null);
        super.new(name, parent);
        instruction_count = 0;
        cycle_count = 0;
        branch_count = 0;
        branch_taken_count = 0;
        branch_not_taken_count = 0;
        load_count = 0;
        store_count = 0;
        exception_count = 0;
        file_opened = 1'b0;
        analysis_export = new("analysis_export", this);
    endfunction
    
    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        
        if (!uvm_config_db#(cpu_config)::get(this, "", "cpu_config", m_config)) begin
            `uvm_fatal(get_name(), "Cannot get cpu_config!")
        end
        
        // 打开trace日志文件
        if (m_config.enable_trace_logging && m_config.log_to_file) begin
            trace_fd = $fopen(m_config.trace_log_path, "w");
            if (trace_fd == 0) begin
                `uvm_fatal(get_name(), $sformatf("Cannot open trace log: %s", 
                          m_config.trace_log_path))
            end
            file_opened = 1'b1;
            
            // 写入日志头（兼容Spike格式）
            $fwrite(trace_fd, "# DUT Execution Trace (Spike-compatible format)\n");
            $fwrite(trace_fd, "# Generated by: cpu_logger\n");
            $fwrite(trace_fd, "# Test: %s\n", m_config.test_elf_path);
            $fwrite(trace_fd, "# Timestamp: %0t\n", $time);  // 
            $fwrite(trace_fd, "# Format: core <id>: 0x<pc> (0x<instr>) <mnemonic>\n");
            $fwrite(trace_fd, "#         3 0x<pc> (0x<reg>) x<reg> 0x<value>\n");
            $fwrite(trace_fd, "# ============================================\n");
            
            `uvm_info(get_name(), $sformatf("Trace log opened: %s", 
                     m_config.trace_log_path), UVM_MEDIUM)
        end
    endfunction
    
    // ========================================================================
    // write - UVM analysis port回调（Logger的唯一职责）
    // ========================================================================
    virtual function void write(cpu_seq_item item);
        string mnemonic;
        
        if (!m_config.enable_trace_logging) return;
        
        // 从monitor接收数据，不直接访问vif
        mnemonic = cpu_get_mnemonic(item.instruction);
        
        // 写入trace文件（兼容Spike格式）
        if (file_opened) begin
            $fwrite(trace_fd, "core   0: 0x%08h (0x%08h) %s\n", 
                   item.pc, item.instruction, mnemonic);
            
            // 记录寄存器写入
            if (m_config.log_register_changes && item.rd_we && item.rd_addr != 0) begin
                $fwrite(trace_fd, "3 0x%08h (0x%02x) x%-2d 0x%08h\n",
                       item.pc, item.rd_addr, item.rd_addr, item.rd_data);
            end
            
            // 记录内存访问
            if (m_config.log_memory_accesses) begin
                if (item.mem_write) begin
                    $fwrite(trace_fd, "# mem_write: addr=0x%08h data=0x%08h\n",
                           item.mem_addr, item.mem_wdata);
                    store_count++;
                end
                if (item.mem_read) begin
                    $fwrite(trace_fd, "# mem_read:  addr=0x%08h data=0x%08h\n",
                           item.mem_addr, item.mem_rdata);
                    load_count++;
                end
            end
            
            // 记录异常
            if (item.exception_occurred) begin
                $fwrite(trace_fd, "# exception: cause=0x%02x tval=0x%08h\n", 
                       item.exception_cause, item.exception_tval);
                exception_count++;
            end
            
            // 定期刷新文件
            if (instruction_count % 1000 == 0) begin
                $fflush(trace_fd);
            end
        end
        
        // 可选：打印到控制台
        if (m_config.log_to_console || m_config.print_execution_trace) begin
            `uvm_info(get_name(), $sformatf("[%0d] PC=0x%08h %s", 
                     item.cycle, item.pc, mnemonic), UVM_HIGH)
        end
        
        // 改进：增强分支统计
        instruction_count++;
        cycle_count = item.cycle;
        if (item.is_branch) begin
            branch_count++;
            if (item.branch_taken) begin
                branch_taken_count++;
            end else begin
                branch_not_taken_count++;
            end
        end
        
    endfunction
    
    // ========================================================================
    // Report Phase - 写入统计摘要并关闭文件
    // ========================================================================
    virtual function void report_phase(uvm_phase phase);
        super.report_phase(phase);
        
        `uvm_info(get_name(), "==========================================", UVM_LOW)
        `uvm_info(get_name(), "    Trace Logging Statistics", UVM_LOW)
        `uvm_info(get_name(), "==========================================", UVM_LOW)
        `uvm_info(get_name(), $sformatf("Total Cycles:       %0d", cycle_count), UVM_LOW)
        `uvm_info(get_name(), $sformatf("Total Instructions: %0d", instruction_count), UVM_LOW)
        `uvm_info(get_name(), $sformatf("Branches:           %0d", branch_count), UVM_LOW)
        
        // ：分支详细统计
        if (branch_count > 0) begin
            real taken_rate = 100.0 * real'(branch_taken_count) / real'(branch_count);
            `uvm_info(get_name(), $sformatf("  - Taken:          %0d (%.1f%%)", 
                     branch_taken_count, taken_rate), UVM_LOW)
            `uvm_info(get_name(), $sformatf("  - Not Taken:      %0d (%.1f%%)", 
                     branch_not_taken_count, 100.0 - taken_rate), UVM_LOW)
        end
        
        `uvm_info(get_name(), $sformatf("Loads:              %0d", load_count), UVM_LOW)
        `uvm_info(get_name(), $sformatf("Stores:             %0d", store_count), UVM_LOW)
        `uvm_info(get_name(), $sformatf("Exceptions:         %0d", exception_count), UVM_LOW)
        
        if (instruction_count > 0) begin
            real cpi = real'(cycle_count) / real'(instruction_count);
            real ipc = real'(instruction_count) / real'(cycle_count);
            `uvm_info(get_name(), $sformatf("CPI:                %.3f", cpi), UVM_LOW)
            `uvm_info(get_name(), $sformatf("IPC:                %.3f", ipc), UVM_LOW)
        end
        
        // 关闭trace文件
        if (file_opened && trace_fd != 0) begin
            // 写入统计摘要
            $fwrite(trace_fd, "\n# ============================================\n");
            $fwrite(trace_fd, "# Execution Summary\n");
            $fwrite(trace_fd, "# Total Cycles:       %0d\n", cycle_count);
            $fwrite(trace_fd, "# Total Instructions: %0d\n", instruction_count);
            $fwrite(trace_fd, "# Branches:           %0d\n", branch_count);
            $fwrite(trace_fd, "#   - Taken:          %0d\n", branch_taken_count);
            $fwrite(trace_fd, "#   - Not Taken:      %0d\n", branch_not_taken_count);
            $fwrite(trace_fd, "# Loads:              %0d\n", load_count);
            $fwrite(trace_fd, "# Stores:             %0d\n", store_count);
            $fwrite(trace_fd, "# Exceptions:         %0d\n", exception_count);
            if (instruction_count > 0) begin
                real cpi = real'(cycle_count) / real'(instruction_count);
                $fwrite(trace_fd, "# CPI:                %.3f\n", cpi);
            end
            $fwrite(trace_fd, "# ============================================\n");
            
            $fclose(trace_fd);
            `uvm_info(get_name(), $sformatf("✓ Trace log saved: %s", 
                     m_config.trace_log_path), UVM_LOW)
        end
        
        `uvm_info(get_name(), "==========================================", UVM_LOW)
    endfunction
    
endclass

`endif